### ISSUE TITLE
ENH: Affiliated package review process TOC and bullets

### ISSUE THREAD

**Issue by pllim** [astropy/project#102]
Now that I have to keep referring to it, I would like to make the following changes:

1. Add a TOC on top with links to jump to the section of interest.
2. Turn the paragraphs into bulleted or numbered lists.

Are this acceptable? If so, I can submit a PR. Please let me know.

cc @hamogu 

This is a follow-up of #90 .

**Comment by hamogu** [comment]
I don't care how it's formatted - whatever makes you happy.

**Comment by astrofrog** [comment]
Same!
