### ISSUE TITLE
Rename repo to astropy_project

### ISSUE THREAD

**Issue by bsipocz** [astropy/project#123]
The repo's name is ambiguous especially when forked and cloned.

**Comment by pllim** [comment]
FWIW, in the meantime, you can also rename your fork's repo name via Settings. For example: https://github.com/pllim/astropy_project

**Comment by astrofrog** [comment]
No strong feelings except that if we do, I really think It should be astropy-project as opposed to astropy_project 😉 Aside from that I can see the reasoning and would be happy with the change.

**Comment by kelle** [comment]
I'm just gonna go ahead and do this. Re-open this issue if there's any fallout which needs to be addressed.
