### ISSUE TITLE
Consider using this repository for other project-wide policies and issues

### ISSUE THREAD

**Issue by astrofrog** [astropy/project#14]
Rather than use this repository just for community engagement issues, we could rename it to something more general and to keep track of many project-wide issues, including many of those discussed at in-person coordination meetings. The repository itself could include documents with processes and policies, and new policies could be suggested either as issues or (better) pull requests.

**Comment by kelle** [comment]
I am on board with this idea! I envision having labels for "finance", "governance", etc.

**Comment by pllim** [comment]
I think we all agreed. Close this issue as resolved?

**Comment by eteq** [comment]
This has been done as of the end of the coordination meeting.  Closing!
