### ISSUE TITLE
Setup pep8speaks comments

### ISSUE THREAD

**Issue by kelle** [astropy/project#32]
As decided at the Coordination meeting, one of us (not me!) needs to setup pep8speaks. Any takers?

**Comment by astrofrog** [comment]
PR to astropy: https://github.com/astropy/astropy/pull/9759 - once this is merged I can enable the bot and we can consider copying the configuration to other repositories.

**Comment by bsipocz** [comment]
The PR to the core package has been merged, so I close this now.
