### ISSUE TITLE
Send an email to the astropy community about the first interim finance committee meeting

### ISSUE THREAD

**Issue by eteq** [astropy/project#44]
Several initial decisions and transparency channels were decided on at the first finance committee meeting, a message should go out to the astropy community about these and how people can keep up on continuing activitities.

These messages can only be set up once the channels are all up and working though.

**Comment by jdswinbank** [comment]
Advertise finance e-mail address, finance Slack channel, running notes, etc.

**Comment by jdswinbank** [comment]
I wanted to make a few additions to the wiki in support of this mail (primarily, adding the Finance Ctte charge), but I don't have access. Should I have? If not, what should our workflow be? I don't think it's possible to make a PR against a wiki.

**Comment by hamogu** [comment]
I received the email in my inbox, so this is obviously done.
Thanks @jdswinbank !
