### ISSUE TITLE
Draft questions about grant rules

### ISSUE THREAD

**Issue by crawfordsm** [astropy/project#47]
We have a number of questions about the administration of the grant, and it would be useful to clarify the rules:

Here are some examples:
What is the period?
Should this extend the period?  
Is there any rules about how the extra money has to be spent? `
How closely do we have to align to the original budget?

Proposal is to collaboratively draft the letter with a deadline of the next Finance committee meeting.

**Comment by hamogu** [comment]
I think we have more time for the deadline - I suggest mid-February. We are not going to send the draft, until the Moore foundation has changed their contact info to Eric.

**Comment by hamogu** [comment]
The answers to these questions are all in the Moore grant contract, thus I'm closing this issue.
